// Package catalogs holds the component catalogs, one file per collector release
// per distribution, and embeds the default distribution into the linter binary.
//
// The files are generated by tools/schemagen from the upstream collector
// sources, one directory per distribution. Each release is written twice: a
// YAML file, which is the readable form meant to be reviewed in pull requests,
// and a JSON file for tools that prefer it. The two carry identical content.
//
// Because the catalogs live at the repository root they can also be consumed
// without cloning or installing anything, by pointing the linter at the raw
// files:
//
//	otelcol-config-lint run --catalog-location \
//	  https://raw.githubusercontent.com/minuk-dev/otelcol-config-lint/main/catalogs \
//	  config.yaml
package catalogs

import "embed"

// FS holds the catalogs shipped with the binary. Only the default distribution
// is embedded; any other one has to come from a --catalog-location.
//
//go:embed contrib/*.yaml
var FS embed.FS
